version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.59
    - 1.16.63
    - 1.17.12
    - 1.17.17
    - 1.17.22
    - 1.17.27
    - 1.17.3
    - 1.17.33
    - 1.17.39
    - 1.17.44
    - 1.17.49
    - 1.17.53
    - 1.17.7
  - dependency-name: ansible
    versions:
    - 2.10.5
    - 2.10.6
    - 2.10.7
    - 3.0.0
    - 3.1.0
    - 3.2.0
